- .docgen.sh
- .travis.yml
- Makefile
- _oasis
Signed-off-by: David Scott <dave.scott@eu.citrix.com>
> travis: auto create API documentation on gh-pages

- .docgen.sh
Signed-off-by: David Scott <dave.scott@eu.citrix.com>
> travis: the docs are in api.docdir

- README.md
- _oasis
- lib/channel.ml
- lib/channel.mli
- lib/client.mli
- lib/protocol.mli
- lib/s.mli
- lib/server.mli
- lwt/nbd_lwt_unix.mli
- also remove a stray Lwt_unix dependency
> Improve the ocamldoc

- ChangeLog
- _oasis
- opam
This is the first release with ppx requirements.
Signed-off-by: David Scott <dave@recoil.org>
> Prepare to release 2.1.0

- opam
Signed-off-by: Euan Harris <euan.harris@citrix.com>
> opam: Add dependency on ppx_sexp_conv

- ChangeLog
- _oasis
- opam
Signed-off-by: David Scott <dave@recoil.org>
> Prepare to release v2.1.1

- lib/s.mli
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Ensure the BLOCK interface exposes page_aligned_block = Cstruct.t

- ChangeLog
- _oasis
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> Prepare to release v2.1.2

- ChangeLog
- _oasis
Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>
> v2.1.2 was already released. Let's do v2.1.3!

- .travis.yml
- ChangeLog
- _oasis
- lib_test/mux_test.ml
- opam
This now exposes the new Mirage 3 APIs.
> Prepare to release v3.0.0

- cli/main.ml
- lib/server.ml
> Close open file descriptors and handle NBD_CMD_DISC correctly

- cli/main.ml
- lib/server.ml
And don't stop the whole server if an exception happens during handling a connection.
> [backport for nbd 2.x] Close open file descriptors and handle NBD_CMD_DISC correctly

- .merlin
> Update .merlin file

- .merlin
> .merlin: don't list findlib libraries of this package

- cli/main.ml
Previously we swallowed these exceptions with Lwt.try_bind, but it is
useful to report them to the user. This commit also makes the cleanup
functions more robust, because now we do not rely on carefully avoiding
double-closing the file descriptors, we just ignore any exceptions that
happen in the cleanup functions.
(cherry picked from commit 1ef61435844b3abb0332abd88c55743863565030)
> [backport to nbd 2.x] NBD server: use Lwt.finalize to propagate exceptions up

- lib/protocol.ml
> [backport for v2.x] Fix flags v2.x

- lib_test/jbuild
- nbd-lwt-unix.opam
- nbd.opam
And require the correct libraries
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> Move the tests to the correct package

- README.md
> README.md: update after porting to jbuider

- .docgen.sh
- .index.html
- .travis-docker-docgen.sh
- .travis.yml
- nbd-lwt-unix.opam
- nbd.opam
:crossed_fingers: 
If we accidentally print GH_TOKEN, Travis should still hide it: https://docs.travis-ci.com/user/best-practices-security/
> Fix documentation upload

- .docgen.sh
- .travis.yml
I've created a `test_doc` branch in this repository to test it, and it works:
* https://travis-ci.org/xapi-project/nbd/jobs/261032550#L2510
* https://github.com/xapi-project/nbd/tree/gh-pages
I'll delete that branch once this PR is merged
> Fix doc uploading, now for real - by using my GitHub token :/

- nbd-lwt-unix.opam
- nbd.opam
> nbd.opam, nbd-lwt-unix.opam: add links to API documentation

- cli/jbuild
- cli/main.ml
- lib/channel.ml
- lib/channel.mli
- lib/protocol.ml
- lib/protocol.mli
- lib/s.ml
- lib/server.ml
- lib_test/test.ml
- lwt/jbuild
- lwt/nbd_lwt_unix.ml
- lwt/nbd_lwt_unix.mli
- nbd.opam
Cherry-pick the relevant commits from master,
then fix up build problems.
> TLS functionality (backport to v2)

- cli/main.ml
- lib/s.ml
- lib/server.ml
- lwt/jbuild
- lwt/nbd_lwt_unix.ml
- lwt/nbd_lwt_unix.mli
- nbd-lwt-unix.opam
Also use those improvements in the CLI tool.
> Improve ease of safe use of library

- cli/main.ml
- lib/client.ml
- lib/mirror.ml
- lib/mux.ml
- lib/protocol.ml
- lib/s.ml
- lib/server.ml
- lib_test/mux_test.ml
> Run "make reindent"

- .coverage.sh
- .travis.yml
- lib/jbuild
- lib_test/jbuild
- lwt/jbuild
- nbd.opam
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> Fix build and coverage

- cli/main.ml
- lib/s.ml
- lib/server.ml
- lwt/jbuild
- lwt/nbd_lwt_unix.ml
- lwt/nbd_lwt_unix.mli
Backported from master:
+ Add functions for ease of safe use
+ Refactor to use them.
> Refactor for ease of safe use (backport)

- ChangeLog
> Prepare to release 2.3.0

- lib_test/jbuild
- lib_test/mux_test.ml
- lib_test/protocol_test.ml
- lib_test/suite.ml
Backport of #94 (there were no conflicts)
> [backport for bugfix-v2.x] Enhance NBD client tests and reorganize test modules

- cli/main.ml
- lib/block_error_printer.ml
- lib/client.ml
- lib/mirror.ml
- lib/mux.ml
- lib/server.ml
- lib_test/mux_test.ml
- lib_test/protocol_test.ml
Backport of https://github.com/xapi-project/nbd/pull/96
> [ backport to v2.x] Move to Lwt_log and add some more log messages

- lib/server.ml
Backport of https://github.com/xapi-project/nbd/pull/99
> [backport for v2.x] Server: Add more logging: log disconnects and log more info about read errors

- lib_test/jbuild
- lib_test/protocol_test.ml
Signed-off-by: Iglói Gábor <gabor.igloi@citrix.com>
> Add server tests and check that we've reached the end of the sequence

- ChangeLog
> Prepare to release 2.5.0

- cli/main.ml
> Use Lwt_unix.bind instead of deprecated Versioned.bind_2

- .docgen.sh
- .index.html
> docs: upload css file and generated index.html

- nbd-tool.opam
- nbd.opam
> Add lwt_log dep to opam files

- lib_test/client_server_test.ml
- lib_test/cstruct_block.ml
- lib_test/protocol_test.ml
- lib_test/suite.ml
* Test that the server handles writes correctly
* Add a new kind of test that connects together the server and client using a pipe and checks their interaction
> Add server write and client<-> server interaction tests

- lwt/nbd_lwt_unix.ml
Signed-off-by: Yang Qian <yang.qian@citrix.com>
> CA-289145: close socket if error occurs when using lwt connect

- .travis.yml
- cli/main.ml
- lib/mirror.ml
- lib_test/mux_test.ml
- lib_test/protocol_test.ml
> CP-29050: Fix compiler warnings and add a new test

- .travis.yml
- cli_test/dune
- cli_test/random_data.sh
- cli_test/suite.ml
Now make test will take about 30s because of this new stress test.
> Test that misbehaving clients do not crash the server

- nbd-lwt-unix.opam
- nbd-tool.opam
- nbd.opam
This restores the commit that got lost by this force push:
```
gaborigloi
*force-pushed the `master` branch from `decadbe9` to `5a773805`*
<https://github.com/xapi-project/nbd|xapi-project/nbd>xapi-project/nbd
```
> Update opam files for Opam 2

- lib_test/protocol_test.ml
This structure is more logical because often the client and server tests
need separate sequences.
> Reorganize protocol tests into client & server tests

- nbd-lwt-unix.opam
- nbd.opam
> Update urls in opam files to point to new version

- lwt/nbd_lwt_unix.ml
Backport of 1fb4c3c
Signed-off-by: Yang Qian <yang.qian@citrix.com>
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>
> XSI-312 CA-289145: close socket if error occurs when using lwt connect

- lib/mirror.ml
- lib/protocol.ml
- nbd-lwt-unix.opam
- nbd-tool.opam
- nbd.opam
As a side-effect, this also brings support for OCaml 4.12
> Add support for cstruct 6.0.0

- nbd-tool.opam
- nbd-unix.opam
- nbd.opam
This should hopefully enable CI to build documentation and upload it.
> opam: add metadata for building documentation

- ChangeLog
- cli/main.ml
- cli_test/suite.ml
- dune-project
- lib/client.ml
- lib/mirror.ml
- lib/mux.ml
- lib/protocol.ml
- lib/protocol.mli
- lib/server.ml
- lib_test/client_server_test.ml
- lib_test/cstruct_block.ml
- lib_test/mux_test.ml
- lib_test/protocol_test.ml
- lib_test/suite.ml
- nbd-tool.opam
- nbd-unix.opam
- nbd.opam
- unix/nbd_unix.ml
- unix/nbd_unix.mli
Removes all warning for a clean compilation with the latest versions of the dependencies
> Update usages of deprecated methods
