- cli/main.ml
Signed-off-by: David Scott <dave.scott@eu.citrix.com>
> cli: don't exit immediately when the mirror is synchronised

- .travis.yml
- ChangeLog
- Makefile
- _oasis
- cli/main.ml
- lib/client.ml
- lib/mirror.ml
- lib/mux.ml
- lib/protocol.ml
- lib/protocol.mli
- lib/server.ml
- lib_test/nbd_test.ml
- lib_test/test.ml
- opam
- remove dead code
- handle the case where the server sends back an unexpected `OptionResponseHeader` (instead of generating a match failed exception)
- add `make reindent` to call `ocp-indent`
- reindent sources
- fix typos in opam file
> Fix warnings, including an inexhaustive match

- .gitignore
- .travis.yml
- _oasis
- cli/main.ml
- lib/client.ml
- lib/mux.ml
- lib/protocol.ml
- lib/protocol.mli
- opam
Also drop the use of lwt.syntax.
This is part of the great cstruct.syntax purge, see
[mirage/ocaml-cstruct#95]
Signed-off-by: David Scott <dave@recoil.org>
> Update to ppx: cstruct.ppx, ppx_sexp_conv

- lib/server.ml
Previously, after NBD_CMD_WRITE, the recursive loop wasn't called again,
and this caused clients to hang when they issued any subsequent
commands.
Fixes #41 
> NBD server: continue processing requests after write command

- cli/main.ml
Previously we swallowed these exceptions with Lwt.try_bind, but it is
useful to report them to the user. This commit also makes the cleanup
functions more robust, because now we do not rely on carefully avoiding
double-closing the file descriptors, we just ignore any exceptions that
happen in the cleanup functions.
> NBD server: use Lwt.finalize to propagate exceptions up

- lib/protocol.ml
Marshal the client flags in the network byte order (big-endian), as
specified by the NBD protocol. Previously these flags were incorrectly
marshalled & unmarshalled as little-endian.
This fix affects both the NBD client and the server: now they will
correctly send and recognize the NBD_FLAG_C_FIXED_NEWSTYLE and
NBD_FLAG_C_NO_ZEROES client flags.
Signed-off-by: Iglói Gábor <gabor.igloi@citrix.com>
Fixes #56
> Fix marshalling & unmarshalling of client flags

- cli/main.ml
To avoid having to wait about 30 seconds until the NBD server can be
started again after shutdown.
> NBD server: set SO_REUSEADDR on the server socket

- cli/main.ml
To avoid having to wait about 30 seconds until the NBD server can be
started again after shutdown.
> [backport for v2.x] NBD server: set SO_REUSEADDR on the server socket

- .coverage.sh
- .travis.yml
- lib/jbuild
- lib_test/jbuild
- lwt/jbuild
Until https://github.com/janestreet/jbuilder/issues/57 is resolved we
can still make coverage builds by adding the necessary flags by hand, as
we are doing for the "old style" ppx derivers.
We watch the value of the `COVERAGE` environment variable. If this is
defined and set to "1", we inject the necessary `ppx_bisect` flags and
dependencies in the generated jbuild file.
The boilerplate necessary is generic and can be used with minimal or no
changes in most of our other packages.
Once the necessary changes are landed in jbuilder and ppx_bisect, we can
update the project simply updating the jbuild files only.
> Fix coverage build using jbuilder (and master ppx_bisect)

- ChangeLog
Note that we've been using the NBD client from this library in xapi, and in other components too. I've tested the reverse dependencies in xs-opam and they still compile. After this PR is merged, I'll update it in xs-opam.
> [bugfix-v2.x] Prepare to release 2.2.0

- ChangeLog
- nbd.opam
to sync the opam file with the one in xs-opam. And prepare a new bugfix release with the fixed `opam` file.
> nbd.opam: require cstruct 2.3.0 instead of 2.4.0

- ChangeLog
- nbd.opam
> nbd.opam: make ppx_sexp_conv bound less restrictive

- lib_test/jbuild
- lib_test/mux_test.ml
- lib_test/protocol_test.ml
- lib_test/suite.ml
Now the tests check that the client wrote the expected output to the
channel, and that it correctly handles the fixed-newstyle handshake and
client flags.
> Enhance NBD client tests and reorganize test modules

- lib/s.ml
- lib/server.ml
- lib_test/protocol_test.ml
This is the same as #106, but without #105, so it just adds support for explicitly marking exports as read-only.
The difference is that this one terminates the session after sending the EPERM error in case the client tries to write to a read-only export. This is what the existing code does in case of *any* write error, but I think this behaviour does not follow the design, see #105 
As I mentioned in #106 , I think we should merge that one instead of this, because NBD_CMD_WRITE did not even work, see #41 , the continuation of the client handling group has been added in  #43
> Server: Add support for read-only exports

- cli/main.ml
- lib/server.ml
This will not have a significant impact on existing users of the
library, because write access did not work until recently.
> Server.serve: set read_only to true by default for safety

- cli/main.ml
- lib/s.ml
- lib/server.ml
This PR ports the following PRs to master from the bugfix-v2.x branch that have already been reviewed:
* https://github.com/xapi-project/nbd/pull/107
* https://github.com/xapi-project/nbd/pull/109
The read-only parameter itself might change when we finalize the new interface of the library.
> [port to master from bugfix-v2.x] Add parameter for serving exports as read-only

- lib/channel.ml
- lib/channel.mli
- lwt/nbd_lwt_unix.ml
- lwt/nbd_lwt_unix.mli
Reverts xapi-project/nbd#114
We're moving to the master branch, so we should put this there. I also made a mistake when I benchmarked this - I measured without a timeout, because the CLI does not use it.
> Revert "CP-24919: Optional timeout for channel IO"

- Makefile
- benchmark.sh
> Add script for benchmarking

- lib/jbuild
- lib_test/jbuild
This patch should be backward compatible
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>
> jbuild: add missing lwt_log

- .docgen.sh
The output of "make doc" has changed, now the HTML docs are in the _html
subdirectory.
> Fix doc upload

- .travis.yml
- lib/client.ml
- lib/s.ml
- lib/server.ml
- lib_test/client_server_test.ml
- lib_test/jbuild
- lib_test/protocol_test.ml
- nbd.opam
Various fixes to make the client and server conform more to the NBD
protocol:
* Ensure Client.list terminates the option haggling by sending an abort.
This change should not cause problems, as currently we don't seem to
use Client.list anywhere.
* Fix the server's response to NBD_OPT_LIST - previously it did not send
the lenghts to the client correctly, and therefore qemu-img and
nbd-client could not list the exports.
* Check that the lengths the export names in the optional ~offer param
passed to Server.connect are below the maximum limit allowed by the NBD
protocol.
* Ensure the server responds to an abort with an ack. This change
shouldn't cause issues either, because we gracefully handle the case
without failing where the client disconnects without waiting for the
ack.
* Clean up …
> CP-29049: Fix list and abort behaviour and expand protocol tests

- .travis.yml
- Makefile
- benchmark.sh
- cli/main.ml
- cli_test/dune
- cli_test/suite.ml
- cli_test/test-nbd-client.sh
- cli_test/test-qemu.sh
- lib_test/dune
- nbd-tool.opam
- nbd.opam
Add an option to specify an export name when serving a file. If
specified, only this export name will be accepted, and the client will
be allowed to list the exports.
If unspecified, the behavior is the same as before: listing the exports
is not allowed, and any export name is accepted.
I've added compatibility tests with qemu-img and nbd-client. By default,
these test are skipped if the required programs aren't installed. If the
strict option is enabled, the tests will fail instead of being skipped.
> Add exportname option to CLI and interop tests

- cli_test/random_data.sh
nmap's netcat returns a non-zero exit code when the server closes the
connection, this caused the stress test to fail.
> Make stress test work on CentOS with nmap's netcat

- cli/main.ml
- lwt/nbd_lwt_unix.ml
- lwt/nbd_lwt_unix.mli
ECDHE ciphersuites are not working at all currently.
After we do this we'll also need to update xapi-nbd to pass `~curve:"secp384r1"`
> CA-307773: initialize EC curves

- cli/main.ml
The cli is used only for debugging so we can safely force the user to
provide a cipherstring.
Signed-off-by: lippirk <ben.anson@citrix.com>
> CP-33058 force cipherstring parameter

- .travis.yml
- lib_test/suite.ml
Note that running the tests in a certain order
causes them to hang. I did not find the cause
of this.
> maintenance: upgrade alcotest to 1.1.0

- .github/workflows/gh-pages.yml
- .github/workflows/ocaml-ci.yml
The wrong option was used when installing opam dependencies.
> ci: fix doc and coverage upload

- .github/workflows/ocaml-ci.yml
- ChangeLog
- cli/dune
- cli/main.ml
- lib/dune
- lib_test/dune
- nbd-unix.opam
- nbd.opam
- unix/dune
Now the dune dependencies are more explicit
fixes #161
> require mirage-block 3.0.0, drop io-page-unix
